defaultContentLanguage: de
title: Henning Dahlheim
baseURL: dahlheim.ch


languages:
  de:
    weight: 1
    LanguageName: German
    menu:
      main:
        # - url: /slides/
        #   name: Präsentationen
        #   weight: 1
        - url: /arbeit/
          name: Arbeit
          weight: 2
  #       - url: "/posts/"
  #         name: "Artikel"
  #         weight: 1
  #       - url: "/about/"
  #         name: "Über mich"
  #         weight: 2
  #       - url: "/uses/"
  #         name: "Werkzeuge"
  #         weight: 3
      social:
      - url: https://github.com/hdahlheim
        name: GitHub
        weight: 1
      - url: https://twitter.com/hactar_
        name: twitter
        weight: 2
    params:
      description: Ich bin ein Fullstack Entwickler aus Basel
  en:
    weight: 1
    LanguageName: Englisch
    menu:
      main:
        - url: /work/
          name: Work
          weight: 1
    #     - url: "/posts/"
    #       name: "Blog"
    #       weight: 1
    #     - url: "/about/"
    #       name: "About"
    #       weight: 2
    #     - url: "/uses/"
    #       name: "My Tools"
    #       weight: 3
      social:
      - url: https://github.com/hdahlheim
        name: GitHub
        weight: 1
      - url: https://twitter.com/hactar_
        name: twitter
        weight: 2
    params:
      description: I’m a Software Developer based in Basel.

pygmentsCodefences: true
pygmentsStyle: "api"
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
