languageCode = "ch-de"
title = "Hello, ich bin Henning"
theme = "dahlheim.ch"

pygmentsCodefences = true
pygmentsStyle = "api"
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true


[menu]

  # [[menu.main]]
  # url    = "/projects"
  # name   = "Projekte"
  # weight = 1

  # [[menu.main]]
  # url    = "/articles"
  # name   = "Artikel"
  # weight = 2

  # [[menu.main]]
  # url    = "/talks"
  # name   = "Presentationen"
  # weight = 3

  [[menu.main]]
  url    = "https://github.com/hdahlheim"
  name   = "Github"
  weight = 4

  # [[menu.main]]
  # url    = "https://twitter.com/hactar_"
  # name   = "Twitter"
  # weight = 4
